---
creation_rules:
  - path_regex: ^baremetal/inventory/host_vars/[^/]+/secrets\.sops\.ya?ml$
    encrypted_regex: '.*'
    key_groups:
      - age:
          - age1akkcd4nm65lekere3zuem7v3fxqxp3sz2mzpqvs9lh98ffq98psqjl9y6r
  - path_regex: ^baremetal/inventory/group_vars/[^/]+\.sops\.ya?ml$
    encrypted_regex: '.*'
    key_groups:
      - age:
          - age1akkcd4nm65lekere3zuem7v3fxqxp3sz2mzpqvs9lh98ffq98psqjl9y6r
  - path_regex: ^docs/secrets/.+\.sops\.ya?ml$
    encrypted_regex: '.*'
    key_groups:
      - age:
          - age1akkcd4nm65lekere3zuem7v3fxqxp3sz2mzpqvs9lh98ffq98psqjl9y6r
