---
# SOPS configuration to ensure secrets remain encrypted at rest.
creation_rules:
  - path_regex: (?:baremetal|vps)/inventory/group_vars/.+\.sops\.ya?ml$
    encrypted_regex: '^(vps_external_dns_api_token|vps_keycloak_admin_password)$'
    key_groups:
      - age:
          - age1examplemanagevariables0000000000000000000000000000000000000000000000000000
  - path_regex: kubernetes/ansible/inventories/.+\.sops\.ya?ml$
    key_groups:
      - age:
          - age1kubernetesmultisite0000000000000000000000000000000000000000000000000
  - path_regex: kubernetes/flux/.+\.sops\.ya?ml$
    key_groups:
      - age:
          - age1kubernetesmultisite0000000000000000000000000000000000000000000000000
