---
# SOPS configuration to ensure secrets remain encrypted at rest.
creation_rules:
  - path_regex: ^baremetal/inventory-local/host_vars/.+/secrets\.sops\.ya?ml$
    encrypted_regex: '^(password_hash|ssh_authorized_keys|.*_secret|.*_passphrase)$'
    key_groups:
      - age:
          - age12j8qqj94jtn7xhg0qc2zwftsfpn7xre4ztfuyk607ha9zqwy4qusyysk09
  - path_regex: ^baremetal/inventory/host_vars/.+/secrets\.sops\.ya?ml$
    encrypted_regex: '^(password_hash|ssh_authorized_keys|.*_secret|.*_passphrase)$'
    key_groups:
      - age:
          - age12j8qqj94jtn7xhg0qc2zwftsfpn7xre4ztfuyk607ha9zqwy4qusyysk09
  - path_regex: ^baremetal/inventory/group_vars/.+\.sops\.ya?ml$
    encrypted_regex: '^(disk_encryption_passphrase|.*_secret)$'
    key_groups:
      - age:
          - age12j8qqj94jtn7xhg0qc2zwftsfpn7xre4ztfuyk607ha9zqwy4qusyysk09
  - path_regex: ^inventory/group_vars/.+\.sops\.ya?ml$
    encrypted_regex: '^(vps_external_dns_api_token|vps_keycloak_admin_password)$'
    key_groups:
      - age:
          - age12j8qqj94jtn7xhg0qc2zwftsfpn7xre4ztfuyk607ha9zqwy4qusyysk09
  - path_regex: ^docs/secrets/.+\.sops\.ya?ml$
    encrypted_regex: '.*'
    key_groups:
      - age:
          - age12j8qqj94jtn7xhg0qc2zwftsfpn7xre4ztfuyk607ha9zqwy4qusyysk09
