---
hostname: dell-optiplex-3020m
hardware_model: dell-optiplex-3020m
storage_profile: sata
netmode: dhcp
nic: enp2s0
disk_device: /dev/sda
extra_packages:
  - intel-microcode
  - thermald
  - powertop
  - lm-sensors
  - linux-tools-generic
enable_powertop_autotune: true
enable_thermald: true
# Secrets spécifiques à l'hôte (clé SSH, hash) doivent provenir des fichiers
# `host_vars/<host>/secrets.sops.yaml`.
