---
hostname: dell-optiplex-3020m
hardware_model: dell-optiplex-3020m
storage_profile: sata
netmode: static
nic: enp2s0
disk_device: /dev/sda
hardware_specs:
  cpu:
    model: intel-core-i5-4590t
    architecture: haswell
    cores: 4
    threads: 4
    turbo_mhz: 3600
  memory:
    total_gb: 8
    type: ddr3
    speed_mhz: 1600
extra_packages:
  - intel-microcode
  - thermald
  - powertop
  - lm-sensors
  - linux-tools-generic
enable_powertop_autotune: true
enable_thermald: true
# Secrets spécifiques à l'hôte (clé SSH, hash) doivent provenir des fichiers
# `host_vars/<host>/secrets.sops.yaml`.
