---
hostname: lenovo-90dq004yfr
hardware_model: lenovo-thinkcentre-m700-90dq004yfr
storage_profile: sata
netmode: dhcp
nic: enp1s0
disk_device: /dev/sda
extra_packages:
  - intel-microcode
  - thermald
  - powertop
  - lm-sensors
  - linux-tools-generic
enable_powertop_autotune: true
# Secrets spécifiques à l'hôte (clé SSH, hash) doivent provenir des fichiers
# `host_vars/<host>/secrets.sops.yaml`.
